"""empty message

Revision ID: 8efea6353fb2
Revises: 
Create Date: 2018-12-09 00:24:39.417892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efea6353fb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('parts', sa.Text(), nullable=True),
    sa.Column('car_model', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
