"""empty message

Revision ID: a7086000065f
Revises: 8efea6353fb2
Create Date: 2018-12-09 13:08:42.087720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7086000065f'
down_revision = '8efea6353fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'value',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'value',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
